name: 'Pull request into development'
on: 
    pull_request:
        branches:
            - develop
    workflow_dispatch:

env:
  FLUTTER_VERSION: "3.10.5"

jobs:
    analysis:
        name: 'Checkout''s very nifty, totally efficient dev pipeline XD ‚ò†Ô∏è üõë'
        runs-on: ubuntu-latest
        defaults:
            run:
              shell: bash
        steps:
            - uses: actions/checkout@v3
            - name: Install Flutter
              uses: britannio/action-install-flutter@v1
              with:
                version: $FLUTTER_VERSION

            - name: Get packages
              run: flutter pub get

            - name: Run linting
              run: flutter analyze

            - name: Run Flutter tests
              run: flutter test

            - name: Build Web üß± - Development
              run: flutter build web -t lib/main_dev.dart

            - name: Deploy Web üöÄ - Development
              uses: w9jds/firebase-action@master
              with:
                args: deploy --only hosting:development
              env:
                FIREBASE_TOKEN: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}

            - name: Build Web üß± - Staging
              run: flutter build web -t lib/main_stg.dart

            - name: Deploy Web üöÄ - Staging
              uses: w9jds/firebase-action@master
              with:
                args: deploy --only hosting:staging
              env:
                FIREBASE_TOKEN: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}

            - name: Build Android üß± - Development
              run: flutter build appbundle --debug --flavor development -t lib/main_dev.dart

            - name: Distribute Android App üß± - Development
              uses: wzieba/Firebase-Distribution-Github-Action@v1
              with:
                app_id: ${{ secrets.CHECKOUT_DEV_FIREBASE_APP_ID }}
                serviceCredentialsFileContent: ${{ secrets.FIREBASE_DEV_SERVICE_ACCOUNT_CONTENT }}
                file: build/app/outputs/bundle/developmentDebug/app-development-debug.aab
                groups: testers


            - name: Build Android üß± - Staging
              run: flutter build appbundle --profile --flavor staging -t lib/main_stg.dart
  
            - name: Distribute Android App üß± - Staging
              uses: wzieba/Firebase-Distribution-Github-Action@v1
              with:
                  app_id: ${{ secrets.CHECKOUT_STAGING_FIREBASE_APP_ID }}
                  serviceCredentialsFileContent: ${{ secrets.FIREBASE_STAGING_SERVICE_ACCOUNT_CONTENT }}
                  file: build/app/outputs/bundle/stagingProfile/app-staging-profile.aab
                  groups: testers
